name: pull-request
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited] # https://frontside.com/blog/2020-05-26-github-actions-pull_request/
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Jest Tests and Coverage
        run: npm run test_coverage
      - uses: vebr/jest-lcov-reporter@v0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    - name: Install Dependencies
      run: npm ci
    - name: Prettify Code
      run: npm run format
    - name: Commit any changes
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    - name: Install Dependencies
      run: npm ci
    - name: Lint Code
      run: npm run lint
    - name: Commit any changes
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
  build:
    needs: [test, format, lint]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    - name: Install Dependencies
      run: npm ci
    - name: Build Code
      run: npm run build
    - name: Commit any changes
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions